local f = dofile("tests/eso_fixture.lua")
local scm, eq = f.scm, f.eq
local tests = {}
local function test(name, fn) tests[#tests + 1] = {name, fn} end
local function draft()
    return { enabled=true, startDate="2026-10-15", startTime="12:00 PM", eventDate="2026-10-16", eventTime="08:00 PM",
        endDate="2026-10-16", endTime="09:00 PM", delivery="REPEAT", intervalMinutes=5,
        messagePhases={a={BEFORE=true}, b={DAY=true}, c={LIVE=true}}, phaseIntervals={DAY=15} }
end
local function setup()
    f.reset()
    scm.scheduleRuntime, scm.chatPopulationQueue = {}, {}
    f.entry("a", "ad", "Amber Traders", "Amber Traders trial Friday at 8 PM EDT.")
    f.entry("b", "ad", "Amber Traders", "Amber Traders trial tonight at 8 PM EDT.")
    f.entry("c", "ad", "Amber Traders", "Amber Traders trial is underway.")
    assert(type(scm.SaveGuildSchedule) == "function", "schedule configuration is missing")
end
test("validated Save stores the expected Eastern instants and enables Scheduled mode", function()
    local ok, reason = scm:SaveGuildSchedule("ad", "Amber Traders", draft())
    assert(ok, reason)
    local s = scm:GetGuildSchedule("ad", "Amber Traders")
    eq(s.startsAtUtc,1792080000); eq(s.eventAtUtc,1792195200); eq(s.endsAtUtc,1792198800)
    eq(scm:GetGuildRunAt("ad", "Amber Traders"), "SCHEDULED")
end)
test("invalid Save is transactional and keeps the previous schedule", function()
    assert(scm:SaveGuildSchedule("ad", "Amber Traders", draft()))
    local previous = scm:GetGuildSchedule("ad", "Amber Traders")
    local invalid = draft(); invalid.endTime="07:00 PM"
    local ok, reason = scm:SaveGuildSchedule("ad", "Amber Traders", invalid)
    eq(ok,false); assert(reason); eq(scm:GetGuildSchedule("ad", "Amber Traders"),previous)
end)
test("window starts inclusively and finishes exclusively even if paused", function()
    assert(scm:SaveGuildSchedule("ad", "Amber Traders", draft()))
    eq(scm:GetGuildScheduleState("ad", "Amber Traders",1792079999),"WAITING")
    eq(scm:GetGuildScheduleState("ad", "Amber Traders",1792080000),"RUNNING")
    eq(scm:GetGuildScheduleState("ad", "Amber Traders",1792198800),"FINISHED")
    scm:GetGuildSchedule("ad", "Amber Traders").paused=true
    eq(scm:GetGuildScheduleState("ad", "Amber Traders",1792198799),"PAUSED")
    eq(scm:GetGuildScheduleState("ad", "Amber Traders",1792198800),"FINISHED")
end)
test("only assigned messages are eligible in the current phase", function()
    assert(scm:SaveGuildSchedule("ad", "Amber Traders", draft()))
    now=1792080000; eq(scm:GetScheduledMessageEntries("ad", "Amber Traders")[1].id,"a")
    now=1792123200; eq(scm:GetScheduledMessageEntries("ad", "Amber Traders")[1].id,"b")
    now=1792195200; eq(scm:GetScheduledMessageEntries("ad", "Amber Traders")[1].id,"c")
    scm.savedVars.messages[3]=nil
    eq(#scm:GetScheduledMessageEntries("ad", "Amber Traders"),0)
end)
test("missing legacy schedule is inactive and old settings remain compatible", function()
    scm:SetGuildRunAt("ad", "Amber Traders", "SCHEDULED")
    eq(scm:GetGuildScheduleState("ad", "Amber Traders",1792080000),"UNCONFIGURED")
    scm:SetGuildRunAt("ad", "Amber Traders", "ON_DEMAND")
    eq(scm:GetGuildScheduleState("ad", "Amber Traders",1792080000),"ON_DEMAND")
end)
test("Save rejects a second enabled scheduled Zone combination", function()
    local d=draft(); d.delivery="ZONE"
    assert(scm:SaveGuildSchedule("ad", "Amber Traders",d))
    f.entry("z","other","Blue Traders","Blue Traders recruiting.")
    local ok, reason=scm:SaveGuildSchedule("other","Blue Traders",d)
    eq(ok,false); assert(reason:find("Zone"))
end)
test("schedule configuration survives reload and additive V1 export/import", function()
    assert(scm:SaveGuildSchedule("ad", "Amber Traders", draft()))
    scm:GetGuildSchedule("ad", "Amber Traders").paused=true
    ZO_SavedVars={NewAccountWide=function() return scm.savedVars end}
    scm:InitializeSavedVars()
    eq(scm:GetGuildSchedule("ad", "Amber Traders").paused,true)
    local exported=scm:BuildExportString()
    local ok, reason=scm:ImportSettingsFromString(exported)
    assert(ok,reason)
    local s=scm:GetGuildSchedule("ad", "Amber Traders")
    eq(s.paused,true); eq(s.messagePhases.b.DAY,true); eq(s.phaseIntervals.DAY,15)
    eq(s.startsAtUtc,1792080000)
end)
local function savedRuntime()
    assert(scm:SaveGuildSchedule("ad","Amber Traders",draft()))
    now=1792080000
end
local function sent()
    local text=CHAT_SYSTEM.textEntry.EditControl.text
    CHAT_SYSTEM.textEntry.EditControl.text=""
    scm:HandleRestoreWatcherChatMessage(2,3,"My Character",text,false,"@Me")
end
test("scheduler activates inside the window and stops at its end", function()
    savedRuntime(); scm:TickSchedules()
    assert(CHAT_SYSTEM.textEntry.EditControl.text:find("Friday"))
    assert(scm.pendingRestoreState.metadata.scheduledDelivery)
    now=1792198800; scm:TickSchedules()
    eq(CHAT_SYSTEM.textEntry.EditControl.text,""); eq(scm.pendingRestoreState,nil)
    eq(scm:IsReminderAutomationActive("ad","Amber Traders"),false)
end)
test("repeat waits for a confirmed send and honors the phase interval", function()
    savedRuntime(); scm:TickSchedules(); sent()
    eq(scm:GetGuildSchedule("ad","Amber Traders").nextDueAt,1792080300)
    now=1792080299; scm:TickSchedules(); eq(CHAT_SYSTEM.textEntry.EditControl.text,"")
    now=1792080300; scm:TickSchedules(); assert(scm.pendingRestoreState)
    sent(); now=1792123200; scm:TickSchedules(); assert(CHAT_SYSTEM.textEntry.EditControl.text:find("tonight"))
    sent(); eq(scm:GetGuildSchedule("ad","Amber Traders").nextDueAt,1792124100)
end)
test("busy player input is preserved and delayed delivery uses the current phase", function()
    savedRuntime(); CHAT_SYSTEM.textEntry.EditControl.text="My personal message"
    scm:TickSchedules(); eq(CHAT_SYSTEM.textEntry.EditControl.text,"My personal message")
    now=1792123200; CHAT_SYSTEM.textEntry.EditControl.text=""; scm:TickSchedules()
    assert(CHAT_SYSTEM.textEntry.EditControl.text:find("tonight"))
end)
test("manual off persists across scheduler restart and peers do not unpause", function()
    savedRuntime(); scm:TickSchedules()
    scm:HandleDynamicSlashCommand("ad","/recruit","1 off")
    eq(scm:GetGuildSchedule("ad","Amber Traders").paused,true)
    scm:InitializeScheduler(); scm:TickSchedules()
    eq(scm.pendingRestoreState,nil)
    f.incoming(3,"Amber Traders trial Friday at 8 PM EDT (about 2h).")
    eq(scm:GetGuildSchedule("ad","Amber Traders").paused,true)
    eq(scm:IsReminderAutomationActive("ad","Amber Traders"),false)
end)
test("peer observation defers active repeat and does not deliver beyond end", function()
    savedRuntime(); scm:TickSchedules(); sent()
    now=1792080100
    f.incoming(3,"Amber Traders trial Friday at 8 PM EDT (about 2h).")
    eq(scm:GetGuildSchedule("ad","Amber Traders").nextDueAt,1792080460)
    now=1792080459; scm:TickSchedules(); eq(scm.pendingRestoreState,nil)
    now=1792198750; scm:TickSchedules()
    f.incoming(3,"Amber Traders trial is underway.")
    now=1792198800; scm:TickSchedules(); eq(scm.pendingRestoreState,nil)
end)
test("late login produces only the current phase and no expired backlog", function()
    savedRuntime(); now=1792195300; scm:InitializeScheduler()
    assert(CHAT_SYSTEM.textEntry.EditControl.text:find("underway"))
    now=1792199000; scm:InitializeScheduler()
    eq(scm.pendingRestoreState,nil)
end)
test("expired schedules preserve even whitespace-only player edits", function()
    savedRuntime(); scm:TickSchedules()
    CHAT_SYSTEM.textEntry.EditControl.text="Player edit"
    now=1792198800; scm:TickSchedules()
    eq(CHAT_SYSTEM.textEntry.EditControl.text,"Player edit")
    eq(scm.pendingRestoreState,nil)
end)
test("manual scheduled requests respect window and pause", function()
    savedRuntime(); now=1792079999
    scm:HandleDynamicSlashCommand("ad","/recruit","1")
    eq(scm.pendingRestoreState,nil)
    now=1792198800; scm:HandleDynamicSlashCommand("ad","/recruit","1")
    eq(scm.pendingRestoreState,nil)
end)
test("scheduled Zone waits for an existing manual Zone owner", function()
    local d=draft(); d.delivery="ZONE"; assert(scm:SaveGuildSchedule("ad","Amber Traders",d))
    f.entry("z","other","Blue Traders","Blue Traders is recruiting.")
    scm:SetGuildAutoPopulateOnZone("other","Blue Traders",true)
    scm:SetActiveAutoPopulate("other","Blue Traders")
    now=1792080000; scm:TickSchedules(); eq(scm.pendingRestoreState,nil)
    eq(scm:GetActiveAutoPopulate().commandId,"other")
    scm:ClearActiveAutoPopulate(); scm:TickSchedules(); assert(scm.pendingRestoreState)
end)
test("deleted phase assignments cannot fall back to another phase", function()
    savedRuntime(); scm.savedVars.messages[1]=nil
    -- Keep the message array contiguous, as real DeleteMessage does.
    table.remove(scm.savedVars.messages,1)
    scm:TickSchedules(); eq(scm.pendingRestoreState,nil)
end)
test("event tokens use the configured Eastern event identity", function()
    savedRuntime()
    eq(scm:ResolveScheduledEventTokens("%eventdate% at %eventtime%: %eventwhen%", "ad", "Amber Traders"), "10/16/2026 at 08:00 PM EDT: tomorrow")
    now=1792123200
    eq(scm:ResolveScheduledEventTokens("%eventwhen%", "ad", "Amber Traders"),"today")
end)
test("incoming event tokens retain event identity while eventwhen and countdown vary", function()
    savedRuntime()
    local entry=scm.savedVars.messages[1]
    entry.text="%guild% trial %eventwhen%, %eventdate% at %eventtime%."
    local function matches(text) return scm:MatchesIncomingMessage(entry,"Amber Traders",scm:NormalizeIncomingChatText(text)) end
    assert(matches("Amber Traders trial tomorrow, 10/16/2026 at 08:00 PM EDT (about 2h)."))
    assert(not matches("Amber Traders trial today, 10/16/2026 at 08:00 PM EDT (about 2h)."))
    now=1792123200
    assert(matches("Amber Traders trial today, 10/16/2026 at 08:00 PM EDT (about 2h)."))
    assert(not matches("Amber Traders trial today, 10/17/2026 at 08:00 PM EDT (about 2h)."))
    assert(not matches("Amber Traders trial whenever, 10/16/2026 at 08:00 PM EDT (about 2h)."))
    local d=draft(); d.eventTime="07:00 PM"; assert(scm:SaveGuildSchedule("ad","Amber Traders",d))
    assert(not matches("Amber Traders trial today, 10/16/2026 at 08:00 PM EDT (about 2h)."))
end)
test("unassigned messages default to ANY and explicit empty assignments disable a message", function()
    local d=draft(); d.messagePhases={}; assert(scm:SaveGuildSchedule("ad","Amber Traders",d)); now=1792080000
    eq(#scm:GetScheduledMessageEntries("ad","Amber Traders"),3)
    scm:GetGuildSchedule("ad","Amber Traders").messagePhases.a={}
    eq(#scm:GetScheduledMessageEntries("ad","Amber Traders"),2)
end)
test("deleting every eligible message withdraws untouched pending scheduled text", function()
    savedRuntime(); scm:TickSchedules(); assert(scm.pendingRestoreState)
    table.remove(scm.savedVars.messages,1); scm:TickSchedules()
    eq(scm.pendingRestoreState,nil); eq(CHAT_SYSTEM.textEntry.EditControl.text,"")
end)
test("manual requests outrank scheduled requests without replacing typed chat", function()
    savedRuntime(); CHAT_SYSTEM.textEntry.EditControl.text="Player typing"; scm:TickSchedules()
    f.entry("manual","other","Blue Traders","Manual message.")
    scm:PopulateChatBufferForCommand("other","Blue Traders")
    eq(CHAT_SYSTEM.textEntry.EditControl.text,"Player typing")
    CHAT_SYSTEM.textEntry.EditControl.text=""; scm:ProcessChatPopulationQueue()
    eq(scm.pendingRestoreState.metadata.commandId,"other")
end)
test("timeout retries wait the interval and expired callbacks do not restart schedules", function()
    savedRuntime(); scm:TickSchedules()
    local callback=EVENT_MANAGER.updates[scm.restoreWatcherTimeoutName].callback
    now=now+60; callback(); eq(scm.pendingRestoreState,nil)
    scm:TickSchedules(); eq(scm.pendingRestoreState,nil)
    now=now+300; scm:TickSchedules(); assert(scm.pendingRestoreState)
    now=1792198800; scm:TickSchedules(); callback(); eq(scm.pendingRestoreState,nil)
    eq(scm:IsReminderAutomationActive("ad","Amber Traders"),false)
end)
test("settings draft validates transactionally and persists message phase edits", function()
    scm.savedVars.selectedMessagesCommand="ad"
    local original=scm.GetSelectedGuildNameForMessages
    scm.GetSelectedGuildNameForMessages=function() return "Amber Traders" end
    scm.scheduleEditor=nil
    local controls=scm:BuildScheduleOptionControls()
    local byName={}
    for _,control in ipairs(controls) do
        if control.name then byName[control.name]=control end
        if control.getFunc then control.getFunc() end
        if control.type=="description" and type(control.text)=="function" then control.text() end
    end
    byName["Save schedule"].func(); eq(scm:GetGuildSchedule("ad","Amber Traders"),nil)
    local d=scm:GetScheduleEditorDraft()
    for k,v in pairs(draft()) do d[k]=v end
    byName["Message number to assign"].setFunc("1")
    byName["Selected message: ANY"].setFunc(false)
    byName["Selected message: DAY"].setFunc(true)
    byName["Save schedule"].func()
    assert(scm:GetGuildSchedule("ad","Amber Traders").messagePhases.a.DAY)
    byName["Pause saved schedule"].func(); eq(scm:GetGuildSchedule("ad","Amber Traders").paused,true)
    byName["Resume saved schedule"].func(); eq(scm:GetGuildSchedule("ad","Amber Traders").paused,false)
    scm.GetSelectedGuildNameForMessages=original
end)
test("queued Zone requests recheck current zone eligibility before delivery", function()
    local d=draft(); d.delivery="ZONE"; assert(scm:SaveGuildSchedule("ad","Amber Traders",d))
    now=1792080000; CHAT_SYSTEM.textEntry.EditControl.text="Typing"; scm:TickSchedules()
    local original=scm.GetEffectiveAutoPopulateZoneId
    scm.GetEffectiveAutoPopulateZoneId=function() return nil end
    CHAT_SYSTEM.textEntry.EditControl.text=""; scm:ProcessChatPopulationQueue()
    eq(scm.pendingRestoreState,nil)
    scm.GetEffectiveAutoPopulateZoneId=original
end)
test("restore timeout preserves edited text and an old callback cannot clear a new request", function()
    savedRuntime(); scm:TickSchedules()
    local old=EVENT_MANAGER.updates[scm.restoreWatcherTimeoutName].callback
    CHAT_SYSTEM.textEntry.EditControl.text="My edit"; now=now+60; old()
    eq(CHAT_SYSTEM.textEntry.EditControl.text,"My edit"); eq(scm.pendingRestoreState,nil)
    CHAT_SYSTEM.textEntry.EditControl.text=""; now=now+300; scm:TickSchedules()
    local pending=scm.pendingRestoreState; assert(pending); old(); eq(scm.pendingRestoreState,pending)
end)
test("busy startup uses lower priority than manual and retains confirmation ownership", function()
    f.entry("m","other","Blue Traders","Manual message.")
    scm:SetGuildRunAt("ad","Amber Traders","STARTUP")
    scm.startupQueueInitialized=true
    scm.startupQueue={{commandId="ad",guildName="Amber Traders",paramText="1"}}
    CHAT_SYSTEM.textEntry.EditControl.text="Typing"; scm:ProcessStartupQueue()
    local queued=scm.chatPopulationQueue[scm:GetReminderStateKey("ad","Amber Traders")]
    assert(queued); eq(queued.priority,2); assert(queued.metadata.startupQueue)
    assert(scm.startupQueueCurrent)
    scm:PopulateChatBufferForCommand("other","Blue Traders")
    CHAT_SYSTEM.textEntry.EditControl.text=""; scm:ProcessChatPopulationQueue()
    eq(scm.pendingRestoreState.metadata.commandId,"other")
    sent(); scm:ProcessChatPopulationQueue(); assert(scm.pendingRestoreState.metadata.startupQueue)
    sent(); eq(scm.startupQueueCurrent,nil)
end)
test("malformed schedule message import returns an error and leaves saved data unchanged", function()
    savedRuntime(); local before=scm:GetGuildSchedule("ad","Amber Traders")
    local export=scm:BuildExportString()
    export=export:gsub("END", "SCHEDULEMESSAGE_V1|ad|amber traders\nEND")
    local ok,reason=scm:ImportSettingsFromString(export)
    eq(ok,false); assert(reason); eq(scm:GetGuildSchedule("ad","Amber Traders"),before)
end)
test("multiple Repeat schedules share chat and retain separate confirmed deadlines", function()
    savedRuntime(); f.entry("o","other","Blue Traders","Blue Traders event.")
    local d=draft(); d.messagePhases={}; assert(scm:SaveGuildSchedule("other","Blue Traders",d))
    scm:TickSchedules(); eq(scm.pendingRestoreState.metadata.commandId,"ad")
    sent(); scm:TickSchedules(); eq(scm.pendingRestoreState.metadata.commandId,"other")
    sent(); scm:TickSchedules(); eq(scm.pendingRestoreState,nil)
    eq(scm:GetGuildSchedule("ad","Amber Traders").nextDueAt,now+300)
    eq(scm:GetGuildSchedule("other","Blue Traders").nextDueAt,now+300)
end)
test("discarded stale startup requests release their current ownership", function()
    scm:SetGuildRunAt("ad","Amber Traders","STARTUP")
    scm.startupQueueInitialized=true; scm.startupQueue={{commandId="ad",guildName="Amber Traders",paramText="1"}}
    CHAT_SYSTEM.textEntry.EditControl.text="Typing"; scm:ProcessStartupQueue()
    assert(scm.startupQueueCurrent)
    scm:SetGuildRunAt("ad","Amber Traders","ON_DEMAND")
    CHAT_SYSTEM.textEntry.EditControl.text=""; scm:ProcessChatPopulationQueue()
    eq(scm.startupQueueCurrent,nil); eq(scm.pendingRestoreState,nil)
end)
test("peer usage while paused advances the due time without resuming", function()
    savedRuntime(); scm:TickSchedules(); sent(); scm:PauseGuildSchedule("ad","Amber Traders")
    now=now+100; f.incoming(CHAT_CHANNEL_ZONE,"Amber Traders trial Friday at 8 PM EDT.")
    eq(scm:GetGuildScheduleState("ad","Amber Traders"),"PAUSED")
    scm:ResumeGuildSchedule("ad","Amber Traders")
    eq(scm:GetScheduledDueAt("ad","Amber Traders","BEFORE"),now+360)
    eq(scm.pendingRestoreState,nil)
end)
local failures=0
for _,case in ipairs(tests) do
    local ok,reason=pcall(function() setup(); case[2]() end)
    if ok then print("PASS "..case[1]) else failures=failures+1; print("FAIL "..case[1]..": "..tostring(reason)) end
end
print(#tests.." schedule tests, "..failures.." failures")
assert(failures==0,"schedule regression suite failed")
